_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
adj_mat_mode:
    value: relative
batch_size:
    value: 1
dataset_name:
    value: rsna-features_resnet18
dropout_prob:
    value: 0.5
early_stopping_patience:
    value: 5
learning_rate:
    value: 0.001
num_epochs:
    value: 10
seed:
    value: 42
use_inst_distances:
    value: false
val_prop:
    value: 0.2
weight_decay:
    value: 0.0001
